version: 2.1
jobs:
  deploy:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run: npm install;
      - run: cd cf-worker && npm install @cloudflare/wrangler && CF_API_KEY=$CLOUDFLARE_API_KEY CF_EMAIL=harrycol97@gmail.com npx wrangler publish;

workflows:
  deploy:
    jobs:
      - deploy:
          context: cf-worker
