version: 2.1
jobs:
  deploy:
    docker:
      - image: cimg/node:lts
      - image: google/cloud-sdk
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - run: npm run build
      - run: cd cf-worker && npm install && CF_API_TOKEN=$CLOUDFLARE_API_TOKEN CLOUD_FLARE_EMAIL=harrycol97@gmail.com npx wrangler pages publish ../build --project-name=portfolio --branch=main
      - run: |
          npm install @google-cloud/deploy
          echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
          gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
          gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
workflows:
  deploy:
    jobs:
      - deploy:
          context: cf-worker
