version: 2.1
jobs:
  deploy:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run: sudo chmod 777 /root
      - run: sudo npm install
      - run: npm install --prefix=$HOME/.local --global serverless
      - run: cd cf-worker
      - run: sudo npm install @cloudflare/wrangler; npx wrangler publish
      - run: sudo chmod 700 /root; sudo chmod -R 700 /root/.wrangler

workflows:
  deploy:
    jobs:
      - deploy:
          context: cf-worker
