version: 2.1
orbs:
  gcp-cli: circleci/gcp-cli@2.1.0

jobs:
  deploy:
    docker:
      - image: cimg/node:lts
      - image: google/cloud-sdk
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - run: npm run build
      - run: cd cf-worker && npm install && CF_API_TOKEN=$CLOUDFLARE_API_TOKEN CLOUD_FLARE_EMAIL=harrycol97@gmail.com npx wrangler pages publish ../build --project-name=portfolio --branch=main

  gae_deploy:
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - gcp-cli/initialize
      - run:
          name: Deploy to Google App Engine
          command: |
            cd server
            gcloud app deploy ./app.yaml

workflows:
  deploy:
    jobs:
      - deploy:
          context: cf-worker
      - gae_deploy:
          filters:
            branches:
              only:
                - main
