version: 2.1
jobs:
  deploy:
    docker:
      - image: cimg/node:19.2.0
    steps:
      - checkout
      - run: yarn install
      - run: cd cf-worker
      - run: yarn add @cloudflare/wrangler -g; wrangler publish

workflows:
  deploy:
    jobs:
      - deploy:
          context: cf-worker
