version: 2.1
jobs:
  deploy:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run: npm install;
      - run: cd cf-worker && ls;
      - run: npm install @cloudflare/wrangler;
      - run: npx wrangler publish;

workflows:
  deploy:
    jobs:
      - deploy:
          context: cf-worker
