version: 4.0.0
jobs:
  deploy:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run: npm install
      - run: npm i @cloudflare/wrangler -g
      - run: wrangler publishs
workflows:
  build-test-deploy:
    jobs:
      - build:
          context: cf-worker
      - test
      - deploy:
          context: cf-worker
