version: 2.1
jobs:
  deploy:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run: sudo npm install
      - run: npm install --prefix=$HOME/.local --global serverless
      - run: sudo npm install @cloudflare/wrangler -g; cd cf-worker/; wrangler publish
workflows:
  deploy:
    jobs:
      - deploy:
          context: cf-worker
