version: 2.1
jobs:
  deploy:
    docker:
      - image: cimg/node:19.2.0
    steps:
      - checkout
      - run: sudo npm install
      # - run: cd cf-worker
      # - run: sudo npm install @cloudflare/wrangler -g; wrangler publish

workflows:
  deploy:
    jobs:
      - deploy:
          context: cf-worker
