version: 2.1
jobs:
  deploy:
    docker:
      - image: cimg/node:lts
    # environment:
    #   CLOUDFLARE_ACCOUNT_ID: $CLOUDFLARE_ACCOUNT_ID
    #   CLOUDFLARE_API_TOKEN: $CLOUDFLARE_API_TOKEN
    steps:
      - checkout
      - run: npm install;
      - run: echo ${CLOUDFLARE_API_KEY}
      - run: cd cf-worker && npm install @cloudflare/wrangler && CF_API_TOKEN=$CLOUDFLARE_API_TOKEN CF_EMAIL=harrycol97@gmail.com npx wrangler publish && npx wrangler pages publish ../build --project-name=portfolio --branch=main

workflows:
  deploy:
    jobs:
      - deploy:
          context: cf-worker
