version: 2.1
jobs:
  deploy:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run: sudo npm install
      - run: sudo npm i @cloudflare/wrangler -g
      - run: wrangler publish
workflows:
  deploy:
    jobs:
      - deploy:
          context: cf-worker
