version: 2.1
jobs:
  deploy:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run: npm install
      # - run: cd cf-worker
      - run: npm install @cloudflare/wrangler -g;
      # - run: wrangler publish

workflows:
  deploy:
    jobs:
      - deploy:
          context: cf-worker
